# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jkl < Formula
  desc "JKL is a version manager for other command-line tools. It installs tools quickly with minimal input, and helps you switch versions of tools while you work."
  homepage "https://github.com/ivanfetch/jkl"
  version "0.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanfetch/testjkl/releases/download/v0.0.11/testjkl_0.0.11_darwin_amd64.tar.gz"
      sha256 "b89d9f439dc80ed4beaa01f5fba51f4e33af6ccefea3b34b726b26c400cab837"

      def install
        bin.install "testjkl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanfetch/testjkl/releases/download/v0.0.11/testjkl_0.0.11_darwin_arm64.tar.gz"
      sha256 "24c9810ba01e290cae62f779a0dd4d12dfef251fbd2ccbbdb64edcbce3bd5b7d"

      def install
        bin.install "testjkl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ivanfetch/testjkl/releases/download/v0.0.11/testjkl_0.0.11_linux_armv6.tar.gz"
      sha256 "8ecff4e4d7ae85a83f3bd262b6fad935f8cb5870ae70785bb376fec9f46d3474"

      def install
        bin.install "testjkl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ivanfetch/testjkl/releases/download/v0.0.11/testjkl_0.0.11_linux_amd64.tar.gz"
      sha256 "431e7a509df3c1c67ba75a6bde328838975a314a677440e40b23271065da6fed"

      def install
        bin.install "testjkl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanfetch/testjkl/releases/download/v0.0.11/testjkl_0.0.11_linux_arm64.tar.gz"
      sha256 "1f571bfd9abb711a77665eb6e21fbefd50d3b4ffd759a360d6e2420bab98f3c0"

      def install
        bin.install "testjkl"
      end
    end
  end

  def caveats
    <<~EOS
      You will need to add the jkl shims directory (default ~/.jkl/bin) to your PATH.
    EOS
  end

  test do
    system "#{bin}/jkl version"
  end
end
